# -*- coding: utf-8 -*-
"""NLP Task – 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVcnWjuCe18rR-G7r5IjXvUVNMvt0dOa
"""

!pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load better instruction-based model
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

print("Chatbot: Hello! I am your AI assistant. Type 'exit' to stop.")

while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit"]:
        print("Chatbot: Goodbye! 👋")
        break

    # Strong instruction prompt for accuracy
    prompt = f"""
    You are a helpful and intelligent AI assistant.
    Always give correct, clear, and simple answers in 1-2 lines.

    If greeting, respond politely.
    If question, give factual answer.

    User: {user_input}
    Assistant:
    """

    inputs = tokenizer(prompt, return_tensors="pt")

    outputs = model.generate(
        **inputs,
        max_length=120,
        do_sample=False,
        num_beams=5
    )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    print("Chatbot:", response)

