# -*- coding: utf-8 -*-
"""NLP_Task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d097jKGfO-IYmsff3YVr7RlwnfCUrXPt
"""

!pip install transformers seqeval

!wget https://raw.githubusercontent.com/UniversalDependencies/UD_English-EWT/master/en_ewt-ud-train.conllu
!wget https://raw.githubusercontent.com/UniversalDependencies/UD_English-EWT/master/en_ewt-ud-dev.conllu

def read_conllu(file):
    sentences = []
    labels = []

    tokens = []
    pos_tags = []

    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or line.strip() == "":
                if tokens:
                    sentences.append(tokens)
                    labels.append(pos_tags)
                    tokens = []
                    pos_tags = []
                continue

            parts = line.strip().split("\t")
            if "-" in parts[0] or "." in parts[0]:
                continue

            tokens.append(parts[1])
            pos_tags.append(parts[3])

    return sentences, labels

train_tokens, train_labels = read_conllu("en_ewt-ud-train.conllu")
val_tokens, val_labels = read_conllu("en_ewt-ud-dev.conllu")

label_list = list(set(tag for sent in train_labels for tag in sent))

label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_and_align(tokens, labels):
    tokenized = tokenizer(
        tokens,
        is_split_into_words=True,
        truncation=True,
        padding='max_length',
        max_length=128
    )

    word_ids = tokenized.word_ids()
    label_ids = []
    prev = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != prev:
            label_ids.append(label2id[labels[word_idx]])
        else:
            label_ids.append(-100)
        prev = word_idx

    tokenized["labels"] = label_ids
    return tokenized

train_data = [tokenize_and_align(t, l) for t, l in zip(train_tokens, train_labels)]
val_data = [tokenize_and_align(t, l) for t, l in zip(val_tokens, val_labels)]

from datasets import Dataset

train_dataset = Dataset.from_list(train_data)
val_dataset = Dataset.from_list(val_data)

from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer)

!pip install -U transformers

from transformers import TrainingArguments, Trainer

args = TrainingArguments(
    output_dir="out",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2
)

from seqeval.metrics import precision_score, recall_score, f1_score

def compute_metrics(p):
    preds, labels = p
    preds = preds.argmax(axis=2)

    true_preds = []
    true_labels = []

    for pred, lab in zip(preds, labels):
        temp_p = []
        temp_l = []
        for p_val, l_val in zip(pred, lab):
            if l_val != -100:
                temp_p.append(id2label[p_val])
                temp_l.append(id2label[l_val])
        true_preds.append(temp_p)
        true_labels.append(temp_l)

    return {
        "precision": precision_score(true_labels, true_preds),
        "recall": recall_score(true_labels, true_preds),
        "f1": f1_score(true_labels, true_preds)
    }

train_dataset = train_dataset.select(range(300))
val_dataset = val_dataset.select(range(100))

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.state.global_step = 0
trainer.state.epoch = 0
trainer.state.is_world_process_zero = True

sentence = "John works at Google in California"

tokens = sentence.split()
inputs = tokenizer(tokens, return_tensors="pt", is_split_into_words=True)

outputs = model(**inputs)
preds = outputs.logits.argmax(dim=2)[0].tolist()

word_ids = inputs.word_ids()
final = []
prev = None

for i, word_idx in enumerate(word_ids):
    if word_idx is None or word_idx == prev:
        continue
    final.append((tokens[word_idx], id2label[preds[i]]))
    prev = word_idx

for word, tag in final:
    print(word, "→", tag)



