# -*- coding: utf-8 -*-
"""GENAI_TASK-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111lE682mlrbI30-HPffv0pl0u691KoJ6
"""

!pip install langchain-core

# Mastering Prompt Templates in LangChain

from langchain_core.prompts import PromptTemplate, ChatPromptTemplate

# -------------------- Task 1 --------------------

template1 = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} in simple terms for beginners"
)

def explain_topic(topic):
    return template1.format(topic=topic)

print("Task 1 Output:")
print(explain_topic("Artificial Intelligence"))


# -------------------- Task 2 --------------------

template2 = PromptTemplate(
    input_variables=["topic", "audience", "tone"],
    template="Explain {topic} for {audience} in a {tone} tone"
)

print("\nTask 2 Output:")
print(template2.format(topic="AI", audience="beginners", tone="friendly"))
print(template2.format(topic="Python", audience="kids", tone="fun"))
print(template2.format(topic="Deep Learning", audience="engineers", tone="technical"))


# -------------------- Task 3 --------------------

teaching_template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} clearly step by step"
)

interview_template = PromptTemplate(
    input_variables=["topic"],
    template="Ask 3 questions about {topic}"
)

story_template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} as a story"
)

print("\nTask 3 Output:")
topic = "Machine Learning"
print(teaching_template.format(topic=topic))
print(interview_template.format(topic=topic))
print(story_template.format(topic=topic))


# -------------------- Task 4 --------------------

chat_template = ChatPromptTemplate.from_messages([
    ("system", "You are a {role}"),
    ("user", "Explain {topic}")
])

def generate_chat(role, topic):
    return chat_template.format_messages(role=role, topic=topic)

print("\nTask 4 Output:")
messages = generate_chat("teacher", "Neural Networks")
for m in messages:
    print(m)


# -------------------- Task 5 --------------------

def validate_inputs(audience, tone):
    valid_audience = ["beginner", "intermediate", "expert"]
    valid_tone = ["formal", "casual", "fun"]

    if audience not in valid_audience:
        audience = "beginner"

    if tone not in valid_tone:
        tone = "formal"
    return audience, tone
print("\nTask 5 Output:")
print(validate_inputs("kids", "friendly"))
# -------------------- Task 6 --------------------
styles = {
    "teaching": "Explain {topic} for {audience} in a {tone} teaching style",
    "interview": "Ask interview questions about {topic} for {audience} in a {tone} tone",
    "storytelling": "Explain {topic} for {audience} in a {tone} storytelling style"
}
def generate_prompt(topic, audience, tone, style):
    audience, tone = validate_inputs(audience, tone)

    template = PromptTemplate(
        input_variables=["topic", "audience", "tone"],
        template=styles[style]
    )

    return template.format(topic=topic, audience=audience, tone=tone)

print("\nTask 6 Output:")
print(generate_prompt("Neural Networks", "beginner", "fun", "storytelling"))
# -------------------- Task 7 -------------------
reuse_template = PromptTemplate(
    input_variables=["topic", "audience", "tone"],
    template="Explain {topic} for {audience} in a {tone} tone"
)
inputs = [
    ("AI", "beginner", "fun"),
    ("Python", "intermediate", "formal"),
    ("Machine Learning", "expert", "casual"),
    ("Deep Learning", "beginner", "formal"),
    ("NLP", "expert", "fun")
]
print("\nTask 7 Output:")
for topic, audience, tone in inputs:
    print(reuse_template.format(topic=topic, audience=audience, tone=tone))
# -------------------- Pipeline --------------------

print("\nPipeline Flow:")
print("User Input → Validation → PromptTemplate → Output")

