# -*- coding: utf-8 -*-
"""NLP_Task-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BKRo7Rozt6B7oT_sqQaxiy-0L9TMSvh
"""

!pip install -q transformers datasets scikit-learn

import numpy as np
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

dataset = load_dataset("imdb")

def clean_text(example):
    example["text"] = example["text"].lower()
    return example

train_data = dataset["train"].map(clean_text)
test_data = dataset["test"].map(clean_text)

train_split = train_data.train_test_split(test_size=0.1)
train_dataset = train_split["train"]
val_dataset = train_split["test"]

train_dataset = train_dataset.select(range(2000))
val_dataset = val_dataset.select(range(500))
test_dataset = test_dataset.select(range(500))

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_data.map(tokenize, batched=True)

train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=1,
    eval_strategy="epoch",
    save_strategy="epoch"
)

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)

    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="binary")

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

test_dataset = test_dataset.select(range(500))

preds = trainer.predict(test_dataset)

y_true = preds.label_ids
y_pred = np.argmax(preds.predictions, axis=1)

print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
print("\nAccuracy:", accuracy_score(y_true, y_pred))
print("\nPrecision, Recall, F1:",
      precision_recall_fscore_support(y_true, y_pred, average="binary"))

